spring.application.name=vidstreamingpoc
server.servlet.context-path=/videostreamingpoc
server.port=8080

config.aws.region=${AWS_REGION:region}
config.aws.access-key-id=${AWS_ACCESS_KEY_ID:accesskey}
config.aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:secretaccesskey}